### ISSUE TITLE
import sfpy does not work in Conda 4.7 macOS 10.13.6

### ISSUE THREAD

**Issue by juandesant** [billzorn/sfpy#2]
After installing sfpy-0.6.0 on the base Anaconda 4.7.11 environment (base python 3.7), if I try to use

    import sfpy

I get the following error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/anaconda3/lib/python3.7/site-packages/sfpy/__init__.py", line 1, in <module>
        from . import posit as softposit
    ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/sfpy/posit.cpython-37m-darwin.so, 2): Symbol not found: _convertDoubleToP16
      Referenced from: /anaconda3/lib/python3.7/site-packages/sfpy/posit.cpython-37m-darwin.so
      Expected in: flat namespace
     in /anaconda3/lib/python3.7/site-packages/sfpy/posit.cpython-37m-darwin.so

I installed Cython with `conda install cython`, and did not make a difference.

This is the output from `uname -a`:

    Darwin hostname 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64

**Comment by billzorn** [comment]
Interesting.

The pip install depends on some static libraries (.a) that are built on Linux - for whatever reason, Linux and Mac don't agree on how the archives should be structured, so the Linux libraries that are currently being used will be ignored by the build on Mac.

Sorry about this - I am trying to find a workaround that doesn't involve building an entirely different package on a Mac, but I haven't sorted everything out yet.

In the meantime, if you need to use the library, you can still build it from source (i.e. check out this repo and follow the build instructions) directly on Mac, and it should work. There are some detailed instructions for this in [building](https://github.com/billzorn/sfpy/blob/master/BUILDING.md), but they aren't the best organized.

Basically, what you will want to do is:

`git clone` (remember to `--recurse-submodules` to get the libraries)

Apply build patches to the libraries:
```
cd SoftPosit
git apply ../softposit_sfpy_build.patch
cd ../berkeley-softfloat-3
git apply ../softfloat_sfpy_build.patch
```

Build the libraries:
`make lib`

Set up a virtual environment for building the package:
```
python3.7 -m venv .env
source .env/bin/activate
pip install --upgrade -r requirements.txt
```

Run Cython:
`make cython`

Build the package:
`make sdist` or `make wheel`

This should give you a package in `dist/`, which you can install from any other Python environment where you want to use it:
`pip install sfpy/dist/sfpy-0.6.0.tar.gz`

I hope this helps - sorry it's so complicated.

Here is a source package build on a friend's Macbook - he was able to successfully install and use it with Python 3.7, but your mileage may vary. [sfpy-mac-0.6.0.tar.gz](https://github.com/billzorn/sfpy/files/3495062/sfpy-mac-0.6.0.tar.gz)
